######################################################################
##  Stuff that needs to happen at 10pm.
######################################################################

- alias: 'Shut down AMP in Living room'
  id: 3b41321c-8242-4cf5-9a93-b2b7aeeb8ea0
  trigger:
    - platform: time
      at: '22:00:00'

  action:
    - wait_template: >-
       {{ not is_state('media_player.livingroomCC', 'playing') }}
    - wait_template: >-
       {{ not is_state('media_player.whole_house', 'playing') }}

    - service: script.speech_engine
      data_template:
        call_no_announcement: 1
        call_garage_check: 1
        call_window_check: 1

    - wait_template: >-
       {{ not is_state('media_player.livingroomCC', 'playing') }}
    - service: switch.turn_off
      entity_id: switch.lr_amp
