# Configuration for welcome - https://github.com/behaviorbot/welcome
# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue here! This is the place to request enhancements, ask questions and other things.  You can also ask questions via X or the YouTube Channel found at https://youtube.com/vCloudInfo

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request! Once @CCOSTAN reviews, we will merge it.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! We here at vCloudInfo appreciate the effort involved in improving code and documentation!

# It is recommended to include as many gifs and emojis as possible!


# Todo Bot Configurations
todo:
  autoAssign: false
  blobLines: 10
  label: false 
  
