#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# Finance - Track stock prices via Yahoo Finance.
#-------------------------------------------
######################################################################
##  Finance tickers via yahoofinance. Docs: https://www.home-assistant.io/integrations/yahoofinance/
######################################################################
# Stocks Tracked:
#   - Tesla (TSLA)
#   - Apple (AAPL)
#   - Amazon (AMZN)
#   - Microsoft (MSFT)
#
# Update Interval: Every 4 hours
#
# Original Repo: https://github.com/CCOSTAN/Home-AssistantConfig
# Blog Post: https://www.vcloudinfo.com/2020/10/how-to-track-stocks-in-home-assistant-using-a-custom-component.html
# Follow me on https://www.vcloudinfo.com/click-here
#-------------------------------------------

yahoofinance:
  scan_interval:
    hours: 4
  symbols:
    - TSLA
    - AAPL
    - AMZN
    - MSFT
    
