#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# More Info : https://www.vcloudinfo.com/2019/03/using-foscam-cameras-with-home-assistant-and-synology.html
#-------------------------------------------
# homeassistant:
#   customize_glob:
#     "*.*_sleep_hours":
#       unit_of_measurement: hours
#       icon: mdi:sleep
#
#       hidden: False
#-------------------------------------------

camera:
  - platform: synology
    url: !secret synology_url
    username: !secret synology_username
    password: !secret synology_password
    timeout: 15
    verify_ssl: False


binary_sensor:
  - platform: rest
    name: "CAMERA1 Motion Sensor"
    resource: !secret camera1_url
    device_class: motion
    scan_interval: 5
    value_template: >-
      {%- if "<motionDetectAlarm>2</motionDetectAlarm>" in value -%}
        {{ true }}
      {%- else -%}
        {{ false }}
      {%- endif -%}
  - platform: rest
    name: "CAMERA2 Motion Sensor"
    resource: !secret camera2_url
    device_class: motion
    scan_interval: 5
    value_template: >-
      {%- if "<motionDetectAlarm>2</motionDetectAlarm>" in value -%}
        {{ true }}
      {%- else -%}
        {{ false }}
      {%- endif -%}
  - platform: rest
    name: "CAMERA3 Motion Sensor"
    resource: !secret camera3_url
    device_class: motion
    scan_interval: 5
    value_template: >-
      {%- if "<motionDetectAlarm>2</motionDetectAlarm>" in value -%}
        {{ true }}
      {%- else -%}
        {{ false }}
      {%- endif -%}
#-------------------------------------------
# Motion Sensors added to other motion sensors in group yaml
#-------------------------------------------
