#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# iOS Debugging - Notification helpers and app diagnostics.
#-------------------------------------------
######################################################################
##  iOS push config and troubleshooting helpers.
######################################################################
# More info: https://github.com/CCOSTAN/Home-AssistantConfig/issues/780 | #168

notify:
#  - platform: ios #Not Needed anymore - 10/04/2020
  - name: ios_family
    platform: group
    services:
      - service: mobile_app_stacey_iphone11
      - service: mobile_app_carlo_maxpro
  - name: ios_parents
    platform: group
    services:
      - service: mobile_app_stacey_iphone11
      - service: mobile_app_carlo_maxpro

mobile_app:

