#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# Neato Support for D7 Connected Botvac - control my [Neato Vacuum](http://amzn.to/2kqnnqu) with Home Assistant.
#-------------------------------------------
# homeassistant:
#   customize_glob:
#     "*.*_sleep_hours":
#       unit_of_measurement: hours
#       icon: mdi:sleep
#
#       hidden: False
#-------------------------------------------
sensor:
  platform: minecraft
  name: Bear Stone
  server: !secret minecraft
#-------------------------------------------
group:
  Minecraft:
    entities:
      - sensor.bear_stone

##############################################################################
###  Automations - Detect when things are not right. Like any Good Watchdog.
##############################################################################
#automation:
#Tweets pushed out to twitter.
automation:
  - alias: Someone on the MC server!
    trigger:
      - platform: state
        entity_id: sensor.bear_stone

    action:
      - service: light.turn_on
        entity_id: light.justin_go
        data_template:
          color_name: >
            {% if states.sensor.bear_stone.state|int == 1 %}
              gold
            {% elif states.sensor.bear_stone.state|int == 2 %}
              green
            {% elif states.sensor.bear_stone.state|int == 3 %}
              blue
            {% else %}
              red
            {% endif %}

      - service_template: >
            {% if states.sensor.bear_stone.state|int > 0 %}
              light.turn_on
            {% else %}
              light.turn_off
            {% endif %}
        entity_id: light.justin_go

      - service: light.turn_on
        entity_id:
          - light.justin_go
        data:
          flash: short
