######################################################################
# @CCOSTAN - Follow Me on X
# For more info visit https://www.vcloudinfo.com/click-here
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# -------------------------------------------------------------------
# n8n Discord Router - Route HA events to Discord
#  Central REST command into n8n's Discord routing webhook
# -------------------------------------------------------------------
# <No related GitHub issue>
# REST endpoint: n8n webhook /discord-router
######################################################################
