#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# Noon Home - Switch and light routines via Alexa Media Player.
#-------------------------------------------
######################################################################
##  Noon Home lighting controls (legacy hardware). https://amzn.to/3fOIPx6
######################################################################
# Routines now use custom Alexa commands (issue #366). Noon no longer supported.

##################################################
## Scripts
## Called in the AWAY / interior_off script to shut all devices down.
##################################################

# script:
#   noon_lights_off:
#     alias: 'Bathroom Noon Lights Off'
#     sequence:

#       - service: media_player.play_media
#         data:
#           entity_id: media_player.master_bathroom
#           media_content_id: 'turn off bathroom lights'
#           media_content_type: custom
