#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# Rachio Sprinkler - Rain skips and seasonal scheduling.
#-------------------------------------------
######################################################################
##  Smart sprinkler controller via Rachio. https://amzn.to/2eoPKBW
######################################################################
# 
# sensor:
#   - platform: mqtt
#     state_topic: "ifttt/rachio/watering_time"
#     name: "Rachio_watering_time"

