#-------------------------------------------
#  Clean data for the Floorplan UI.
#-------------------------------------------
homeassistant:
  customize_glob:
    "sensor.floorplan_*":

      hidden: True
      homebridge_hidden: True
    "sensor.clock_*":

      hidden: True
      homebridge_hidden: True
#---Sensor for Time and Date.-----------------------------
sensor:
  - platform: template
    scan_interval: 30000
    sensors:
      floorplan_date:
        friendly_name: 'Date'
        entity_id: []
        value_template: >-
          {{now().strftime("%A")}}, {{now().strftime("%B")}} {{now().strftime("%d")}}

  - platform: template
    scan_interval: 60
    sensors:
      floorplan_time:
        friendly_name: 'Time'
        entity_id: []
        value_template: >-
          {{now().strftime("%-I")}}:{{now().strftime("%M")}} {{now().strftime("%p")}}
      clock_time:
        friendly_name: 'Clock Time'
        entity_id: []
        value_template: >-
          {{now().strftime("%-I")}}:{{now().strftime("%M")}}

  - platform: template
    scan_interval: 30000
    sensors:
      clock_am_pm:
        friendly_name: 'AM/PM'
        entity_id: []
        value_template: >-
          {{now().strftime("%p")}}
      clock_day:
        friendly_name: 'Day'
        entity_id: []
        value_template: >-
          {{now().strftime("%A")}}
      clock_date:
        friendly_name: 'Clock Date'
        entity_id: []
        value_template: >-
          {{now().strftime("%B")}} {{now().strftime("%d")}} {{now().year}}
