######################################################################
# @CCOSTAN - Follow Me on X
# For more info visit https://www.vcloudinfo.com/click-here
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# -------------------------------------------------------------------
# YouTube Channel - Track vCloudInfo channel stats via YouTube sensor.
# -------------------------------------------------------------------
# Based on Pinkywafer's package: https://github.com/pinkywafer/Home-Assistant_Config/blob/master/packages/youtube/vcloudinfo.yaml
# Issue reference: https://github.com/CCOSTAN/Home-AssistantConfig/issues/720
sensor:
  - platform: youtube
    channel_id: UC301G8JJFzY0BZ_0lshpKpQ
