language: python

python: "3.8"

before_install:
  - touch fake_key.pem
  - mv config/travis_secrets.yaml config/secrets.yaml

install:
  - pip3 install homeassistant
  - pip3 install colorlog
  - pip3 install python-dateutil
  - git clone https://github.com/custom-components/youtube.git youtube_component/
  - mv youtube_component/custom_components config/custom_components
  - git clone https://github.com/mrk-its/homeassistant-blitzortung.git blitzortung_component/  
  - mv blitzortung_component/custom_components config/custom_components
  
script:
  - hass -c config/ --script check_config --info all
