homeassistant:
  name: Bear Stone Run 
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customize  

http:
  base_url: !secret http_base_url
  api_password: !secret http_api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  trusted_networks:
    - 192.168.10.0/24
    - 127.0.0.1
  ip_ban_enabled: True
  login_attempts_threshold: 3
  
frontend:
panel_iframe:
  router:
    title: 'Router'
    icon: 'mdi:router-wireless'
    url: 'http://192.168.10.1'
  
group: !include_dir_merge_named group
device_tracker: !include_dir_merge_list device_tracker
discovery:
updater:
sun:

light:
  - platform: hue
    host: 192.168.10.75
    allow_unreachable: true
    allow_in_emulated_hue: false
    allow_hue_groups: false

# Reference : https://www.flexfireleds.com/pages/Comparison-between-3528-LEDs-and-5050-LEDs.html    
  - platform: flux_led
    automatic_add: True 
    devices:
      192.168.10.150:
        name: Garage_Left
        mode: "rgb"
      192.168.10.167:
        name: Garage_Small
        mode: "rgb"
      192.168.10.168:
        name: Outdoor_Den
        mode: "rgb"
        
emulated_hue:
  host_ip: 192.168.10.10
  listen_port: 8300
  expose_by_default: false
    
ifttt:
  key: !secret ifttt_key

# history:

logbook:
  exclude:
    entities:
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.garadget_small_status
      - sensor.garadget_large_status
      - sensor.garadget_small_time_in_state
      - sensor.garadget_large_time_in_state
      - sensor.garadget_large_wifi_signal_strength
      - sensor.garadget_small_wifi_signal_strength
      - sensor.garadget_small_reflection_rate
      - sensor.garadget_large_reflection_rate
      - group.garage_doors
      - sensor.time
      - sensor.date
#logger:
#  default: info
recorder:
  purge_days: 7

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret MQTT_username
  password: !secret MQTT_password
  
zwave:
 usb_path: /dev/ttyACM0
 config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config
  
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  
climate:
  platform: nest

media_player:
  platform: cast
  host: 192.168.10.105  

sleepiq:
  username: !secret sleepiq_username
  password: !secret sleepiq_password
  
tts:
  - platform: google
    language: 'en-us'
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    
cover:
  platform: garadget
  covers:
      !secret garadget_large_id:
        username: !secret garadget_username
        password: !secret garadget_password
        name: Garadget Large
      !secret garadget_small_id:  
        username: !secret garadget_username
        password: !secret garadget_password
        name: Garadget Small      
  
sensor: !include_dir_merge_list sensor
automation: !include_dir_merge_list automation
scene: !include_dir_merge_list scene
switch: !include_dir_merge_list switch
script: !include_dir_merge_named script
input_boolean: !include_dir_merge_named input_boolean

