- name: TV Time
  entities:
       light.m1_front_left:
           state: on
           rgb_color: &gold [255,223,0]
           brightness: 100
       light.m1_front_right:
           state: on
           rgb_color: *gold
           brightness: 100
       light.main_slider:
           state: off
       light.m1_back_right:
           state: on
           rgb_color: *gold
           brightness: 50
       light.m1_back_left:
           state: on
           rgb_color: *gold
           brightness: 50
       light.tv_stand_light:
           state: on
           rgb_color: *gold
           brightness: 150
       light.tv_light:
           state: on
           rgb_color: *gold
           brightness: 150
       light.couch_1:
           state: on
           rgb_color: *gold
           brightness: 255

- name: Red_living_Room
  entities:
      light.m1_front_left:
          state: on
          rgb_color: &red [255,0,0]
          brightness: 150
      light.m1_front_right:
          state: on
          rgb_color: *red
          brightness: 150
      light.m1_back_right:
          state: on
          rgb_color: *red
          brightness: 150
      light.m1_back_left:
          state: on
          rgb_color: *red
          brightness: 150
      light.tv_stand_light:
          state: on
          rgb_color: *red
          brightness: 255
      light.tv_light:
          state: on
          rgb_color: *red
          brightness: 255
      light.couch_1:
          state: on
          rgb_color: *red  
          brightness: 255

- name: Living_Room_Daytime_Cool
  entities:
      light.m1_front_left:
          state: on
          kelvin: 5500
          brightness: 255
      light.m1_front_right:
          state: on
          kelvin: 5500
          brightness: 255
      light.m1_back_right:
          state: on
          kelvin: 5500
          brightness: 255
      light.m1_back_left:
          state: on
          kelvin: 5500
          brightness: 255
      light.tv_stand_light:
          state: on
          kelvin: 5500
          brightness: 200
      light.tv_light:
          state: on
          kelvin: 5500
          brightness: 200
      light.couch_1:
          state: on
          kelvin: 5500
          brightness: 255

- name: Living_Room_Evening_Amber
  entities:
      light.m1_front_left:
          state: on
          kelvin: 2700
          brightness: 200
      light.m1_front_right:
          state: on
          kelvin: 2700
          brightness: 200
      light.m1_back_right:
          state: on
          kelvin: 2700
          brightness: 200
      light.m1_back_left:
          state: on
          kelvin: 2700
          brightness: 200
      light.tv_stand_light:
          state: on
          kelvin: 2700
          brightness: 170
      light.tv_light:
          state: on
          kelvin: 2700
          brightness: 170
      light.couch_1:
          state: on
          kelvin: 2700
          brightness: 220
