- name: TV Time
  entities:
       light.m1_front_left:
           state: off
           transition: 10
       light.m1_front_right:
           state: off
           transition: 10
       light.m1_slider:
           state: off
           transition: 10
       light.m1_back_right:
           state: on
           transition: 10
           rgb_color: [255,215,0]   # Gold
           brightness: 30
       light.m1_back_left:
           state: on
           transition: 40
           rgb_color: [255,215,0]   # Gold
           brightness: 30
       light.tv_stand_light:
           state: on
           transition: 400
           rgb_color: [255,215,0]   # Gold
           brightness: 150
       light.tv_light:
           state: on
           transition: 400
           rgb_color: [255,215,0]   # Gold
           brightness: 125
       light.couch_1:
           state: on
           transition: 400
           rgb_color: [255,215,0]   # Gold
           brightness: 255

- name: Red_living_Room
  entities:
      light.m1_front_left:
          state: off
          transition: 10
      light.m1_front_right:
          state: off
          transition: 10
      light.m1_slider:
          state: off
          transition: 10
      light.m1_back_right:
          state: on
          transition: 10
          rgb_color: [255,0,0]   # RED
          brightness: 30
      light.m1_back_left:
          state: on
          transition: 40
          rgb_color: [255,0,0]   # RED
          brightness: 30
      light.tv_stand_light:
          state: on
          transition: 400
          rgb_color: [255,0,0]   # RED
          brightness: 150
      light.tv_light:
          state: on
          transition: 400
          rgb_color: [255,0,0]   # RED
          brightness: 125
      light.couch_1:
          state: on
          transition: 400
          rgb_color: [255,0,0]   # RED
          brightness: 255
