##########  ############################################################
##  Announce when people come or go.
## Announce over all Chromecast Audios
######################################################################
- alias: 'Guest Mode Audio Feedback'

  trigger:
    - platform: state
      entity_id:
        - input_boolean.guest_mode
      from: 'off'
      to: 'on'

  action:
    - service: script.speech_engine
      data_template:
        value1: >
          {{ [
          "Guest Mode has been enabled for the rest of the day.",
          "Switching to guest mode! ",
          "I have enabled guest mode for the rest of the day. ",
          "System Guest Mode has been enabled. I will minimize the amount of automation for today.",
          "Look but do not touch mode enabled.  Otherwise known as Guest Mode around here.",
          "Guest mode enabled or as I like to call it, Look but do not touch mode.",
          "Awesome! I will take the rest of the day off.  Guest mode has been enabled.",
          "Guest Mode enabled.  In other words, Manual Mode engaged.",
          "Guest mode enabled.  Have Fun!",
          "Family, Friends and Fun.  Guest mode has been enabled today.",
          "Guest Mode enabled.  I am still doing stuff behind the scenes but probably will not turn off the lights on you."
          ] | random }}
        call_responsibilities: 1
        call_no_announcement: 1
        call_garage_check: 1
        call_window_check: 1

- alias: 'Guest Mode Reset'

  trigger:
    - platform: state
      entity_id:
        - group.family
      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'on'

  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.guest_mode
    - service: script.speech_engine
      data_template:
        value1: >
          {{ [
          "Guest Mode has been disabled and normal automations will continue.",
          "Let me disable guest mode since there are no longer any guests in the house. ",
          "I have disabled guest mode and have resumed normal operations! ",
          "Disabling guest mode! "
          ] | random }}
        call_no_announcement: 1
