######################################################################
# @CCOSTAN - Follow Me on X
# For more info visit https://www.vcloudinfo.com/click-here
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# -------------------------------------------------------------------
# Infrastructure View - APT updates (3-column layout)
#  Paste this view into the Infrastructure dashboard (storage mode).
# -------------------------------------------------------------------
# Notes: Uses `sensor.docker_*` entities from `config/packages/apt_updates.yaml`.
######################################################################

title: "Infrastructure - APT Updates"
path: infrastructure-apt-updates
icon: mdi:package-up
type: sections
max_columns: 3
sections:
  - type: grid
    columns: 3
    cards:
      - type: entities
        title: docker_10
        show_header_toggle: false
        entities:
          - entity: sensor.docker_10_apt_status
          - entity: sensor.docker_10_apt_last_check
          - entity: sensor.docker_10_apt_last_update
          - entity: sensor.docker_10_apt_reboot_status

      - type: entities
        title: docker_14
        show_header_toggle: false
        entities:
          - entity: sensor.docker_14_apt_status
          - entity: sensor.docker_14_apt_last_check
          - entity: sensor.docker_14_apt_last_update
          - entity: sensor.docker_14_apt_reboot_status

      - type: entities
        title: docker_69
        show_header_toggle: false
        entities:
          - entity: sensor.docker_69_apt_status
          - entity: sensor.docker_69_apt_last_check
          - entity: sensor.docker_69_apt_last_update
          - entity: sensor.docker_69_apt_reboot_status
