###################################################
## * [Nest Thermostats](http://amzn.to/2eAhB1k)
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
###################################################

- platform: nest
  monitored_conditions:
#     - 'temperature'
#     - 'target'
     - 'humidity'
#     - 'operation_mode'
#     - 'last_connection'
#     - 'co_status'
#     - 'smoke_status'

- platform: template
  sensors:
     upstairs_away_mode:
       entity_id: []
       value_template: "{{ is_state_attr('climate.upstairs', 'away_mode', 'on') }}"

- platform: template
  sensors:
     downstairs_away_mode:
       entity_id: []
       value_template: "{{ is_state_attr('climate.downstairs', 'away_mode', 'on') }}"
