##############################################################################
###  Detect when things are on and forgotten about. Like any Good Watchdog.
##############################################################################

##############################################################################

- alias: "NOTIFY IF IP CHANGES"
  id: 88a58d11-28bd-48e1-a674-bc53ee3d8016

  trigger:
    - platform: state
      entity_id: sensor.ipchange
      from: 'False'
      to: 'True'
  action:
    - service: script.notify_engine
      data_template:
        value1: 'Changed IP address:'
        value2: "New IP: {{ states('sensor.exteral_ip') }}"
        value3: ' - Be sure to Change DNS!'
        who: 'carlo'
        apns_id: 'ip-change'

    - service: script.tweet_engine_no_image
      data_template:
        tweet: >
          {{ [
          "That's weird. Looks like my IP address changed. @CCostan, please check it out.",
          "Time to update @GoDaddy @CCostan. Looks like my IP address changed."
          ] | random + " #HomeAutomation"}}
##############################################################################
