sensor.bedroom_alarm_panel:
  friendly_name: 'Bedroom Alarm Panel'

  hidden: False
  homebridge_hidden: True




sensor.entry_alarm_panel:
  friendly_name: 'Entry Alarm Panel'

  hidden: False
  homebridge_hidden: True




sensor.alexa_echo:
  friendly_name: 'Alexa Echo'

  hidden: False
  homebridge_hidden: True
  icon: mdi:amazon



sensor.amazon_dot:
  friendly_name: 'Amazon Dot'

  hidden: False
  homebridge_hidden: True
  icon: mdi:amazon



sensor.amazon_fire_stick:
  friendly_name: 'Fire Stick'

  hidden: False
  homebridge_hidden: True
  icon: mdi:fire



sensor.carlo_6s_battery_level:
  friendly_name: 'Carlo 6s+ Battery Level'

  hidden: False
  homebridge_hidden: True
  icon: mdi:battery-40



sensor.carlo_6s_battery_state:
  friendly_name: 'Carlo 6s+ Battery State'

  hidden: False
  homebridge_hidden: True
  icon: mdi:power-plug-off



sensor.carlopihole:
  friendly_name: 'Pi Hole Server'

  hidden: False
  homebridge_hidden: true
  icon: mdi:filter-variant



sensor.chromecast_audio_1:
  friendly_name: 'Chromecast Audio 1'

  hidden: False
  homebridge_hidden: True
  icon: mdi:music-circle



sensor.chromecast_audio_2:
  friendly_name: 'Chromecast Audio 2'

  hidden: False
  homebridge_hidden: True
  icon: mdi:music-circle



sensor.circle:
  friendly_name: 'Disney Circle'

  hidden: False
  homebridge_hidden: True
  icon: mdi:google-circles-group



sensor.study_ap:
  friendly_name: 'Cisco Main Ap'

  hidden: False
  homebridge_hidden: True
  icon: mdi:router-wireless



sensor.dark_sky_cloud_coverage:
  friendly_name: 'Dark Sky Cloud Coverage'

  hidden: False
  homebridge_hidden: True
  icon: mdi:weather-partlycloudy



sensor.dark_sky_daily_max_precip_intensity:
  friendly_name: 'Dark Sky Daily Max Precip Intensity'

  hidden: False
  homebridge_hidden: True
  icon: mdi:thermometer



sensor.dark_sky_humidity:
  friendly_name: 'Outdoor Humidity'

  hidden: False
  homebridge_hidden: True
  icon: mdi:water-percent



sensor.dark_sky_minutely_summary:
  friendly_name: 'Current Conditions'

  hidden: True
  homebridge_hidden: True
  icon: mdi:beach



sensor.dark_sky_precip_intensity:
  friendly_name: 'Rainfall'

  hidden: False
  homebridge_hidden: True
  icon: mdi:weather-rainy



sensor.dark_sky_temperature:
  friendly_name: 'Outdoor Temp'

  hidden: False
  homebridge_hidden: True
  icon: mdi:thermometer



sensor.dark_sky_wind_speed:
  friendly_name: 'Dark Sky Wind Speed'

  hidden: False
  homebridge_hidden: True
  icon: mdi:weather-windy



sensor.date:
  friendly_name: 'Date'

  hidden: True
  homebridge_hidden: True
  icon: mdi:calendar



sensor.disk_use_percent_:
  friendly_name: 'Disk Usage'

  hidden: False
  homebridge_hidden: True
  icon: mdi:harddisk



sensor.downstairs_away_mode:
  friendly_name: 'Downstairs Away Mode'

  hidden: True
  homebridge_hidden: True




sensor.downstairs_thermostat_humidity:
  friendly_name: 'Downstairs Thermostat Humidity'

  hidden: False
  homebridge_hidden: True
  icon: mdi:water-percent



sensor.downstairs_thermostat_hvac_state:
  friendly_name: 'Downstairs Thermostat Hvac State'

  hidden: True
  homebridge_hidden: True




sensor.downstairs_thermostat_operation_mode:
  friendly_name: 'Downstairs Thermostat Operation Mode'

  hidden: True
  homebridge_hidden: True




sensor.downstairs_thermostat_target:
  friendly_name: 'Downstairs Thermostat Target'

  hidden: True
  homebridge_hidden: True




sensor.downstairs_thermostat_temperature:
  friendly_name: 'Downstairs Thermostat Temperature'

  hidden: True
  homebridge_hidden: True




sensor.external_ip:
  friendly_name: 'External Ip'

  hidden: True
  homebridge_hidden: True




sensor.floorplan_date:
  friendly_name: 'Date'

  hidden: True
  homebridge_hidden: True




sensor.floorplan_time:
  friendly_name: 'Time'

  hidden: True
  homebridge_hidden: True




sensor.ha_installed_version:
  friendly_name: 'Ha Installed Version'

  hidden: False
  homebridge_hidden: True




sensor.ha_uptime:
  friendly_name: 'Ha Uptime'

  hidden: False
  homebridge_hidden: True


sensor.hue_hub_1:
  friendly_name: 'Hue Hub 1'

  hidden: False
  homebridge_hidden: True
  icon: mdi:router-wireless



sensor.hue_hub_2:
  friendly_name: 'Hue Hub 2'

  hidden: False
  homebridge_hidden: True
  icon: mdi:router-wireless



sensor.ipchange:
  friendly_name: 'Ipchange'

  hidden: True
  homebridge_hidden: True




sensor.justins_room_nest_protect_battery_health:
  friendly_name: 'Justins Room Nest Protect Battery Health'

  hidden: True
  homebridge_hidden: True






sensor.large_garage:
  friendly_name: 'Large Garage'

  hidden: False
  homebridge_hidden: True
  icon: mdi:car-connected



sensor.large_garage_reflection_rate:
  friendly_name: 'Reflection Rate'

  hidden: False
  homebridge_hidden: True




sensor.large_garage_status:
  friendly_name: 'State Of The Door'

  hidden: False
  homebridge_hidden: True




sensor.large_garage_time_in_state:
  friendly_name: 'Time In State'

  hidden: False
  homebridge_hidden: True
  icon: mdi:timer-sand



sensor.large_garage_wifi_signal_strength:
  friendly_name: 'Wifi Strength'

  hidden: False
  homebridge_hidden: True
  icon: mdi:wifi



sensor.last_message:
  friendly_name: 'Last Message'

  hidden: False
  homebridge_hidden: True


sensor.medicine_time:
  friendly_name: 'Medicine Time'

  hidden: False
  homebridge_hidden: True




sensor.moon:
  friendly_name: 'Moon'

  hidden: False
  homebridge_hidden: True
  icon: mdi:brightness-3



sensor.nest_downstairs:
  friendly_name: 'Downstairs Nest'

  hidden: True
  homebridge_hidden: True
  icon: mdi:air-conditioner



sensor.nest_upstairs:
  friendly_name: 'Upstairs Nest'

  hidden: True
  homebridge_hidden: True
  icon: mdi:air-conditioner



sensor.nodemcu1:
  friendly_name: 'Nodemcu1'

  hidden: False
  homebridge_hidden: True
  icon: mdi:alarm-bell



sensor.nodemcu2:
  friendly_name: 'Nodemcu2'

  hidden: False
  homebridge_hidden: True
  icon: mdi:alarm-bell



sensor.nodemcu3:
  friendly_name: 'Nodemcu3'

  hidden: False
  homebridge_hidden: True
  icon: mdi:alarm-bell


sensor.pihole_ads_blocked_today:
  friendly_name: 'Ads Blocked Today'

  hidden: False
  homebridge_hidden: true
  icon: mdi:do-not-disturb



sensor.pihole_ads_percentage_blocked_today:
  friendly_name: 'Pi-Hole Ads Percentage Blocked Today'

  hidden: False
  homebridge_hidden: True
  icon: mdi:close-octagon-outline



sensor.pihole_dns_queries_today:
  friendly_name: 'Dns Queries Today'

  hidden: False
  homebridge_hidden: true
  icon: mdi:note-text



sensor.pihole_dns_unique_clients:
  friendly_name: 'Pi-Hole Dns Unique Clients'

  hidden: False
  homebridge_hidden: True
  icon: mdi:account-outline



sensor.printer:
  friendly_name: 'Printer'

  hidden: False
  homebridge_hidden: True
  icon: mdi:printer



sensor.process_homebridge:
  friendly_name: 'Apple Homekit'

  hidden: False
  homebridge_hidden: true
  icon: mdi:memory



sensor.process_mosquitto:
  friendly_name: 'Mosquitto'

  hidden: False
  homebridge_hidden: true
  icon: mdi:memory



sensor.process_node:
  friendly_name: 'Dash Button Monitor'

  hidden: False
  homebridge_hidden: true
  icon: mdi:memory



sensor.rgb_led_garage_large:
  friendly_name: 'Rgb Led Garage Large'

  hidden: False
  homebridge_hidden: True
  icon: mdi:led-on



sensor.rgb_led_garage_small:
  friendly_name: 'Rgb Led Garage Small'

  hidden: False
  homebridge_hidden: True
  icon: mdi:led-on



sensor.rgb_led_outdoor_den:
  friendly_name: 'Rgb Led Outdoor Den'

  hidden: False
  homebridge_hidden: True
  icon: mdi:led-on



sensor.samsungtv:
  friendly_name: 'Samsung Tv'

  hidden: False
  homebridge_hidden: True
  icon: mdi:television



sensor.last_boot:
  friendly_name: 'Since Last Boot'

  hidden: True
  homebridge_hidden: True
  icon: mdi:clock



sensor.last_boot_templated:
  friendly_name: 'Raspberry Pi Uptime'

  hidden: False
  homebridge_hidden: True
  icon: mdi:clock-start


sensor.sleep_number_bed:
  friendly_name: 'Sleep Number Bed'

  hidden: False
  homebridge_hidden: True
  icon: mdi:hotel



sensor.sleepnumber_carlo_carlo_sleepnumber:
  friendly_name: 'Carlo Sleepnumber'

  hidden: False
  homebridge_hidden: True
  icon: mdi:hotel



sensor.sleepnumber_carlo_stacey_sleepnumber:
  friendly_name: 'Stacey Sleepnumber'

  hidden: False
  homebridge_hidden: True
  icon: mdi:hotel



sensor.small_garage:
  friendly_name: 'Small Garage'

  hidden: False
  homebridge_hidden: True
  icon: mdi:car-connected



sensor.small_garage_reflection_rate:
  friendly_name: 'Reflection Rate'

  hidden: False
  homebridge_hidden: True




sensor.small_garage_status:
  friendly_name: 'State Of The Door'

  hidden: False
  homebridge_hidden: True




sensor.small_garage_time_in_state:
  friendly_name: 'Time In State'

  hidden: False
  homebridge_hidden: True
  icon: mdi:timer-sand



sensor.small_garage_wifi_signal_strength:
  friendly_name: 'Wifi Strength'

  hidden: False
  homebridge_hidden: True
  icon: mdi:wifi



sensor.smart_water_meter:
  friendly_name: 'Smart Water Meter'

  hidden: False
  homebridge_hidden: True
  icon: mdi:water



sensor.speedtest_download:
  friendly_name: 'Download'

  hidden: False
  homebridge_hidden: True
  icon: mdi:speedometer



sensor.speedtest_upload:
  friendly_name: 'Upload'

  hidden: False
  homebridge_hidden: True
  icon: mdi:speedometer



sensor.tablotv:
  friendly_name: 'Tablo Tv'

  hidden: False
  homebridge_hidden: True
  icon: mdi:television-guide



sensor.time:
  friendly_name: 'Time'

  hidden: True
  homebridge_hidden: True
  icon: mdi:clock



sensor.unifi_ap:
  friendly_name: 'Unifi Ap'

  hidden: False
  homebridge_hidden: True
  icon: mdi:router-wireless



sensor.upstairs_away_mode:
  friendly_name: 'Upstairs Away Mode'

  hidden: True
  homebridge_hidden: True


sensor.upstairs_thermostat_humidity:
  friendly_name: 'Upstairs Thermostat Humidity'

  hidden: False
  homebridge_hidden: True
  icon: mdi:water-percent


sensor.upstairs_thermostat_hvac_state:
  friendly_name: 'Upstairs Thermostat Hvac State'

  hidden: True
  homebridge_hidden: True




sensor.upstairs_thermostat_operation_mode:
  friendly_name: 'Upstairs Thermostat Operation Mode'

  hidden: True
  homebridge_hidden: True




sensor.upstairs_thermostat_target:
  friendly_name: 'Upstairs Thermostat Target'

  hidden: True
  homebridge_hidden: True




sensor.upstairs_thermostat_temperature:
  friendly_name: 'Upstairs Thermostat Temperature'

  hidden: True
  homebridge_hidden: True




sensor.wii:
  friendly_name: 'Wii'

  hidden: False
  homebridge_hidden: True
  icon: mdi:gamepad-variant



sensor.withings_scale:
  friendly_name: 'Withings Scale'

  hidden: False
  homebridge_hidden: True
  icon: mdi:scale-bathroom
