###################################
##  ZWave Section -
##  Home Assistant runs on my [Raspberry Pi 3](https://amzn.to/2e3DOBY) with [Aeon Labs Z Wave Stick (GEN 5)](https://amzn.to/2eAiAP0).
###################################

##############################################################
- alias: Garage Light Hallway Helper OPEN
  id: 5ea2a2b5-e3de-4acd-823c-dac3eeaa6118
  
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_door
      to: 'on'
    - platform: state
      entity_id: binary_sensor.mcu1_gpio12
      to: 'on'

  condition:
    - condition: state
      entity_id: light.garage_hallway
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        -  light.garage_hallway

##############################################################
- alias: Garage Light Hallway Helper Closed
  id: f6060cd7-add7-487f-9b2b-f7849db3b36d
  
  trigger:
    - platform: state
      entity_id: binary_sensor.mcu1_gpio12
      to: 'off'
      for:
        seconds: 15
    - platform: state
      entity_id: binary_sensor.kitchen_door
      to: 'off'
      for:
        seconds: 15

  condition:
    - condition: state
      entity_id: binary_sensor.mcu1_gpio12
      state: 'off'
    - condition: state
      entity_id: binary_sensor.kitchen_door
      state: 'off'
    - condition: state
      entity_id: light.garage_hallway
      state: 'on'

  action:
    service: light.turn_off
    entity_id: light.garage_hallway

##############################################################
- alias: Shutdown Helper light
  id: 124f95f6-78ca-4c22-9348-1f3a1da2d803
  
  trigger:
    - platform: state
      entity_id: light.k4
      to: 'on'
      for: '00:20:00'
    - platform: state
      entity_id: binary_sensor.hallway_pantry
      to: 'off'
    - platform: state
      entity_id: binary_sensor.hallway_linen
      to: 'off'

  condition:
    condition: state
    entity_id: light.k1
    state: 'off'

  action:
    - service: light.turn_off
      entity_id: light.k4
