######################################################################
# config/automation/tv_time_on_and_off.yaml
# TV Time: soften house lights when living room media starts after 8pm/sunset.
# https://github.com/CCOSTAN/Home-AssistantConfig
######################################################################

- alias: TV Time
  id: 6e59d312-661f-40da-bb08-416f2e86b566
  trigger:
    - platform: state
      entity_id: media_player.living_room_ultra
      to: 'playing'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: home
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
      - condition: time
        after: '20:00:00'
      - condition: state
        entity_id: media_player.living_room_ultra
        state: 'playing'

  action:

    - service: light.turn_off
      entity_id:
        - light.dinette_lights
        - light.kitchen_lights

    - service: switch.turn_on
      entity_id: group.kitchen_Accents

    - service: scene.turn_on
      entity_id: scene.tv_time
