###################################
##  ZWave Section -
##  Home Assistant runs on my [Raspberry Pi 3](https://amzn.to/2e3DOBY) with [Aeon Labs Z Wave Stick (GEN 5)](https://amzn.to/2eAiAP0).
###################################

##############################################################
- alias: Shutdown Helper light
  id: e3f4beff-4fa8-42e3-be5a-32b45106ac8a
  
  trigger:
    - platform: state
      entity_id: light.k4
      to: 'on'
      for: '00:20:00'

  condition:
    condition: state
    entity_id: light.k1
    state: 'off'

  action:
    - service: light.turn_off
      entity_id: light.k4
