######################################################################
# @CCOSTAN - Follow Me on X
# For more info visit https://www.vcloudinfo.com/click-here
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# -------------------------------------------------------------------
# Logbook Configuration - Activity/Logbook display controls
#  Defines what is hidden from the Activity/logbook view to keep noise down.
# -------------------------------------------------------------------
# Notes: Filters vcloudinfo availability chatter plus location/weather noise.
######################################################################

exclude:
  domains:
    - persistent_notification
    - update
  entity_globs:
    - sensor.*_location
    - sensor.*_place
    - sensor.*_geocoded_location  
    - sensor.pirateweather_*
    - weather.*
    - input_text.l10s_vacuum_*
    - input_datetime.l10s_vacuum_*
    - input_boolean.l10s_vacuum_*
    - sensor.*_battery
    - sensor.*_battery_state
    - sensor.*_uptime*
    - sensor.*_last_update*
    - sensor.*_since
    - sensor.*_last_boot
    - sensor.sun_next_*
    - sensor.*_activity
    - sensor.*_bssid
    - sensor.*_wifi_signal_strength
    - "*alarm_panel_1*"
    - "*alarm_panel_2*"
  entities:
    - automation.cuckoo_clock
    - automation.detect_lights_and_adjust_the_brightness_when_turned_on_based_on_time
    - binary_sensor.office_motion
    - binary_sensor.vcloudinfo_com
    - binary_sensor.refrigerator_door_open
    - binary_sensor.rheem_wh_running
    - sensor.vcloudinfo_com
    - group.garage_doors
    - media_player.LivingRoomCC
    - sensor.date
    - sensor.downstairs_ac_cooling_numeric
    - sensor.ha_uptime
    - sensor.large_garage_reflection_rate
    - sensor.large_garage_status
    - sensor.large_garage_time_in_state
    - sensor.large_garage_wifi_signal_strength
    - sensor.pi_hole_ads_blocked_today
    - sensor.pi_hole_ads_percentage_blocked_today
    - sensor.pi_hole_dns_queries_today
    - sensor.rheem_wh_running_state
    - sensor.phyn_water_flowing
    - sensor.sleepnumber_carlo_carlo_pressure
    - sensor.sleepnumber_carlo_stacey_pressure
    - sensor.small_garage_reflection_rate
    - sensor.small_garage_status
    - sensor.small_garage_time_in_state
    - sensor.small_garage_wifi_signal_strength
    - sensor.time
    - sensor.upstairs_ac_cooling_numeric
    - sensor.vcloudinfo_com
