doors:
  name: Doors
  entities:
    - binary_sensor.hallway_linen
    - binary_sensor.hallway_pantry
    - binary_sensor.kitchen_door
    - binary_sensor.MCU2_GPIO12 # Main Slider
    - binary_sensor.MCU3_Light  # Alarm Door
