Interior_Lights:
  entities:
    - group.master_bathroom_accents
    - group.bedroom_lights
    - group.living_room_lights
    - group.living_room_accents
    - group.dinette_lights
    - group.dining_room_lights
    - group.den_lights
    - group.foyer_lights
    - group.office_lights
    - group.hallway_lights
    - group.kitchen_lights
    - group.kitchen_accents
    - group.upstairs_lights
    - group.outdoor_pool_lights
    - group.garage_lights
    - group.paiges_room
    - group.justins_room

Exterior_Lights:
  entities:
    - light.outdoor_bathroom
    - light.outside_pool_lights
    - group.outdoor_pool_lights
    - group.outdoor_front_lights
    - group.landscaping
