Interior_Lights:
  entities:
    - group.master_bathroom_accents
    - group.kitchen_accents
    - light.bedroom
    - light.bedroom_lights
    - light.den_lights
    - light.dinette_lights
    - light.dining_room_lights
    - light.foyer_lights
    - light.garage_lights
    - light.hallway_lights
    - light.kitchen_lights
    - light.living_room_accents
    - light.living_room_lights
    - light.office_lights
    - light.outdoor_front_lights
    - light.outdoor_pool_lights
    - light.outside_pool_lights
    - light.upstairs_lights

Exterior_Lights:
  entities:
    - light.outdoor_bathroom
    - light.outside_pool_lights
    - light.outdoor_pool_lights
    - light.outdoor_front_lights
    - group.landscaping
    - group.outdoor_xmas_lights
