motion:
  name: Motion Detectors
  entities:
    - binary_sensor.office_motion
    - binary_sensor.entry_alarm_panel
    - binary_sensor.bedroom_alarm_panel
    - binary_sensor.camera1_motion_sensor
    - binary_sensor.camera2_motion_sensor
    - binary_sensor.camera3_motion_sensor
