Interior Switches:
  entities:
    - switch.kitchen_accent_1
    - switch.kitchen_accent_2
    - switch.front_door_outlet
    - switch.lr_amp
    - switch.master_bathroom_accent_1
    - switch.master_bathroom_accent_2
    - switch.pool_deck
    - switch.foyer_outlet
    - switch.den_outlet
    - switch.living_room_outlet

Kitchen Accents:
  entities:
    - switch.kitchen_accent_1
    - switch.kitchen_accent_2

Master Bathroom Accents:
  entities:
    - switch.master_bathroom_accent_1
    - switch.master_bathroom_accent_2

Outdoor Seasonal:
    - switch.outside_1
    - switch.xmas1
    - switch.xmas2
    - switch.xmas3
    - switch.xmas4
