Interior Switches:
  entities:
    - switch.den_outlet
    - switch.living_room_outlet
    - switch.foyer_outlet
    - switch.kitchen_accents
    - switch.kitchen_accent_2
    - switch.printer_outlet
    - switch.front_door_outlet
    - switch.garage_outlet
    - switch.lr_amp
    - switch.master_bathroom_accents
    - switch.master_bathroom_accents_2
    - switch.pool_deck
    - switch.1412_2_Outlet
    - switch.1412_3_Outlet
