Weather:
  entities:
    - climate.downstairs
    - sensor.downstairs_thermostat_humidity
    - binary_sensor.downstairs_nest_away
    - climate.upstairs
    - sensor.upstairs_thermostat_humidity
    - binary_sensor.upstairs_nest_away
    - sensor.dark_sky_cloud_coverage
    - sensor.dark_sky_minutely_summary
#    - sensor.dark_sky_nearest_storm_distance
    - sensor.dark_sky_precip_intensity
    - sensor.dark_sky_daily_max_precip_intensity
    - sensor.dark_sky_wind_speed
    - sensor.dark_sky_humidity
    - sensor.dark_sky_temperature
    - sensor.dark_sky_uv_index
    - sensor.moon
    - binary_sensor.iss
    - sensor.launch_window
    - sensor.next_launch
    - camera.wu_doppler_weather
