######################################################################################################
###Script to shut switches with a 30 second delay to not trample codes
###  Sample Call
#  action:
#   - service: script.interior_off
######################################################################################################

interior_off:
  sequence:
    - service: homeassistant.turn_off
      entity_id:
        - group.interior_lights
    - service: script.switch_turn_off_all
    - service: script.paige_lights_off  # C by GE Lights  (https://amzn.to/30w3UWy)
    - service: script.garage_lights_off  # C by GE Lights  (https://amzn.to/30w3UWy)
    - service: script.noon_lights_off   # Noon Home Smart Lights (https://amzn.to/3fOIPx6)
    - service: media_player.turn_off
      entity_id:
        - group.media_players
