#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
######################################################################################################
###Script to send out image appropriate links to YouTube based articles and videos.
######################################################################################################

tweet_youtube_engine_setup:
   sequence:
    - service: script.tweet_engine_image
      data_template:
        who: '{{ who }}'
        tweet: >-
          {%- macro tweet(topic) -%}
            {% set tweets = {
              "ThrowBack": [
                "One of the most popular #SmartHome Projects I have done: (https://www.vcloudinfo.com/2017/07/visualizing-smart-home-using-home.html)",
                "This project was one of the most popular: (https://www.vcloudinfo.com/2017/11/building-digital-cuckoo-clock-with-home.html)",
                "Some of the Best Home Assistant resources around! (https://www.vcloudinfo.com/2018/04/some-of-my-favorite-home-assistant.html)",
                "My Journey to Docker (https://www.vcloudinfo.com/2018/02/journey-to-docker.html)",
                "My Popular DIY Motion Sensor  - (https://www.vcloudinfo.com/2017/11/yet-another-inexpensive-motion-sensor.html)",
                "Build your own DIY Outdoor Smart Home LED strips - (https://www.vcloudinfo.com/2017/08/diy-outdoor-smart-home-led-strips.html)",
                "Breakdown of the entire smart home - (https://www.vcloudinfo.com/2017/07/my-smart-home-look-at-parts-that-make.html)",
                "Build your own Home Alarm System - (https://www.vcloudinfo.com/2017/06/building-my-home-alarm-system-hardware.html)",
                "Adding a Mixer and AMP to this Text to Speech solution changed the Smart Home COMPLETELY! (https://www.vcloudinfo.com/2017/07/giving-voice-to-smart-home.html)",
                "Some of my favorite #Docker Containers that I am using - (https://www.vcloudinfo.com/2018/06/rolling-out-some-new-docker-containers.html)",
                "Be Sure to follow all of my Twitter Accounts! @CCostan and my HOUSE bot @BearStoneHA!",
                "If you are not subscribed to my Smart Home YouTube channel, come join us now! (https://youtube.com/vCloudInfo)",
                "My Full Smart Home diagram and #IOT icon set that you can download to build your own! - (https://www.vcloudinfo.com/2018/07/the-bear-stone-home-assistant-icon.html),"
                "Be sure to like me on Facebook and join our HA group! (https://www.facebook.com/groups/HomeAssistant/) (https://www.facebook.com/VMwareInfo/) (https://www.facebook.com/BearStoneHA/)",
                "You can see how ALL of this is done by browsing my GitHub Repository (https://github.com/CCOSTAN/Home-AssistantConfig#logo)",
                "10 year safety check.  If you have not done it yet, you need to! (https://www.vcloudinfo.com/2017/06/psa-check-out-your-smoke-detectors-once.html)"
              ],
              "S01E01": [
                "Tesla Solar Panels vs #Hurricane IRMA! (https://www.vcloudinfo.com/2018/09/re-installing-tesla-solar-panels-again.html)"
              ],
              "S01E02": [
                "How to Port Forward SageCom 5260 Fast Routers (https://www.vcloudinfo.com/2018/09/setting-up-port-forwarding-on-sagemcom.html)"
              ],
              "S01E03": [
                "Please stop saying #Alexa in your Videos! (https://www.vcloudinfo.com/2018/09/please-stop-saying-alexa-in-your.html)"
              ],
              "S01E04": [
                "Unboxing and setup of the Philips #Hue Calla Landscape Lights (https://www.vcloudinfo.com/2018/09/unboxing-philips-hue-calla-landscape.html)"
              ],
              "S01E05": [
                "Upgrading Home Assistant in #Docker (https://www.vcloudinfo.com/2018/10/upgrading-home-assistant-in-docker.html)"
              ],
              "S01E06": [
                "Adding #Hue Lights to my Smart Home (https://www.vcloudinfo.com/2018/10/adding-smart-light-to-my-smart-house.html)"
              ],
              "S01E07": [
                "Lights, Camera, Automation! #Hue light setup Part 2. (https://www.vcloudinfo.com/2018/10/lights-camera-automation-hue-light.html)"
              ],
              "S01E08": [
                "How to enable #Alexa Whisper Mode and Hunches! (https://www.vcloudinfo.com/2018/10/how-to-enable-alexa-whisper-mode-and.html)"
              ],
              "S01E09": [
                "Siri Store and Retrieve #shortcuts for ANY information! (https://www.vcloudinfo.com/2018/10/siri-store-and-retrieve-shortcuts-for.html)"
              ],
              "S01E10": [
                "Easy Smart Home #Gadgets I use for my Holiday Lighting setup! (https://www.vcloudinfo.com/2018/10/easy-smart-home-gadgets-i-use-for-my.html)"
              ],
              "S01E11": [
                "Port Forwarding on the ARRIS TG1682 Modem Router (https://www.vcloudinfo.com/2018/11/port-forwarding-on-arris-tg1682-modem.html)"
              ],
              "S01E12": [
                "Alexa Parental Controls: Enabling #Explicit Filter mode (https://www.vcloudinfo.com/2018/11/cortana-meet-alexa.html)"
              ],
              "S01E13": [
                "Cortana, Meet #Alexa! (https://www.vcloudinfo.com/2018/11/alexa-parental-controls-enabling.html)"
              ],
              "S01E14": [
                "Routine Tasks; Upgrading Home Assistant to Latest #Beta! (https://www.vcloudinfo.com/2018/11/routine-tasks-upgrading-home-assistant.html)"
              ],
              "S01E15": [
                "Routine Tasks; Adding #Tesla PowerWall sensors to my Home Assistant! (https://www.vcloudinfo.com/2018/11/routine-tasks-adding-tesla-powerwall.html)"
              ],
              "S01E16": [
                "Breaking down my Home Assistant Volume Control (https://www.vcloudinfo.com/2018/12/breaking-down-my-home-assistant-volume.html)"
              ],
              "S01E17": [
                "Volume Control using #Alexa Routines (https://www.vcloudinfo.com/2018/12/volume-control-using-alexa-routines.html)"
              ],
              "S01E18": [
                "How to Weatherproof your Outdoor Smart Plugs on the Cheap! (https://www.vcloudinfo.com/2018/12/how-to-waterproof-your-outdoor-smart.html)"
              ],
              "S01E19": [
                "Automate your home using Amazon Routines! No Software Needed!(https://www.vcloudinfo.com/2018/12/automate-your-home-using-amazon.html)"
              ],
              "S01E20": [
                "Fixing my Home Assistant Breaking Changes with #Atom! (https://www.vcloudinfo.com/2018/12/fixing-my-home-assistant-breaking.html)"
              ],
              "S01E21": [
                "The Epson XP-7100 Small-in-One Printer review and Unboxing (https://www.vcloudinfo.com/2018/12/the-epson-xp-7100-small-in-one-printer.html)"
              ],
              "S02E01": [
                "Enabling Guest Mode TTS feedback for Home Assistant (https://www.vcloudinfo.com/2019/01/enabling-guest-mode-tts-feedback-for.html)"
              ],
              "S02E02": [
                "My DIY weather resistant Wi-Fi switch – 1 Month Later! (https://www.vcloudinfo.com/2019/01/my-diy-weather-resistant-wi-fi-switch-1.html)"
              ],
              "S02E03": [
                "My UI is terrible.  Here is why I do not care. (https://www.vcloudinfo.com/2019/01/lovelace-is-now-standard-i-dont-care.html)"
              ],
              "S02E04": [
                "How to Upgrade Home Assistant Ubuntu to 18.04.1 LTS (https://www.vcloudinfo.com/2019/02/how-to-upgrade-home-assistant-ubuntu-to-18-04-1-lts.html)"
              ],
              "S02E05": [
                "Everyday Holiday Smart Lights – Valentines Day Edition (https://www.vcloudinfo.com/2019/02/everyday-holiday-smart-lights-valentines-day-edition.html)"
              ],
              "S02E06": [
                "How to set up Home Assistant Presence Detection using NMAP (https://www.vcloudinfo.com/2019/02/how-to-set-up-home-assistant-presence-detection-using-nmap.html)"
              ],
              "S02E07": [
                "Breaking down the Flag Sensor in Home Assistant (https://www.vcloudinfo.com/2019/02/breaking-down-the-flag-sensor-in-home-assistant.html)"
              ],
              "S02E08": [
                "How I Upgraded Home Assistant – fixing all the breaking Changes! (https://www.vcloudinfo.com/2019/02/how-i-upgraded-home-assistant-to-0-88-1-fixing-all-the-breaking-changes.html)"
              ],
              "S02E09": [
                "Amazon Discontinues the Dash Button (https://www.vcloudinfo.com/2019/02/amazon-discontinues-the-dash-button.html)"
              ],
              "S02E10": [
                "How to add Garadget to Home Assistant (https://www.vcloudinfo.com/2019/03/how-to-add-garadget-to-home-assistant.html)"
              ],
              "S02E11": [
                "Revisiting the Pi on Pi Day with Home Assistant (https://www.vcloudinfo.com/2019/03/revisiting-the-pi-on-pi-day-with-home-assistant.html)"
              ],
              "S02E12": [
                "How to Setup IP Camera Viewer on your Roku TV (https://www.vcloudinfo.com/2019/03/how-to-setup-ip-cameras-on-your-roku-tv.html)"
              ],
              "S02E13": [
                "Home Assistant upgrade! (https://www.vcloudinfo.com/2019/03/home-assistant-0-90-release-upgrade.html)"
              ],
              "S02E14": [
                "Using Foscam cameras with Home Assistant and Synology (https://www.vcloudinfo.com/2019/03/using-foscam-cameras-with-home-assistant-and-synology.html)"
              ],
              "S02E15": [
                "How to manually upgrade your Synology Surveillance System firmware (https://www.vcloudinfo.com/2019/04/how-to-manually-upgrade-your-synology-surveillance-system-firmware.html)"
              ],
              "S02E16": [
                "Dell P2719H Monitors Setup and Unboxing (https://www.vcloudinfo.com/2019/04/home-office-with-dell-p2719h-monitors-setup-and-unboxing.html)"
              ],
              "S02E17": [
                "Wyze Sense and Camera Unboxing (https://www.vcloudinfo.com/2019/05/20-wyze-sense-and-camera-unboxing-early-access-program.html)"
              ],
              "S02E18": [
                "Google is shutting down the Works with Nest API. (https://www.vcloudinfo.com/2019/05/google-is-shutting-down-the-works-with-nest-api.html)"
              ],
              "S02E19": [
                "How to Setup Alexa Guard Mode and ADT Pulse to monitor your Smart Home (https://www.vcloudinfo.com/2019/05/how-to-setup-alexa-guard-mode-and-adt-pulse-to-monitor-your-smart-home.html)"
              ],
              "S02E20": [
                "Home Assistant Breaking Change: All Light Groups (https://www.vcloudinfo.com/2019/06/home-assistant-breaking-change-all-light-groups.html)"
              ],
              "S02E22": [
                "How to use Template conditions in Home Assistant (https://www.vcloudinfo.com/2019/06/how-to-use-template-conditions-in-home-assistant.html)"
              ],
              "S02E25": [
                "How to upgrade #Docker #Cockpit on #Ubuntu 18.04 (https://www.vcloudinfo.com/2019/07/how-to-upgrade-docker-cockpit-on-ubuntu-18-04.html)"
              ],
              "S02E26": [
                "Upgrading Home Assistant and Fixing icon_template warning errors (https://www.vcloudinfo.com/2019/07/upgrading-home-assistant-and-fixing-icon_template-warning-errors.html)"
              ],
              "S02E27": [
                "How to Add Philips Hue to Home Assistant (and clean your YAML) (https://www.vcloudinfo.com/2019/08/how-to-add-philips-hue-hub-to-home-assistant-and-clean-your-yaml.html)"
              ],
              "S02E28": [
                "How to add Smart Landscaping lights to your Yard with Home Assistant (https://www.vcloudinfo.com/2019/08/how-to-add-smart-landscaping-lights-to-your-yard-with-home-assistant.html)"
              ],
              "S02E29": [
                "LED Solar Spot lights for my Outdoor Tree! (https://www.vcloudinfo.com/2019/08/led-solar-spot-lights-for-my-outdoor-tree.html)"
              ],
              "S02E30": [
                "Swapping Etekcity RF outlets to Tuya Wi-Fi switch outlets! (https://www.vcloudinfo.com/2019/08/swapping-etekcity-rf-outlets-to-tuya-wi-fi-switch-outlets.html)"
              ],
              "S02E31": [
                "I couldn't wait to get RID of this thing! (https://www.vcloudinfo.com/2019/08/unboxing-the-echo-show-5-and-setup.html)"
              ],
              "S02E32": [
                "Charge your car like your Phone! (https://www.vcloudinfo.com/2019/09/charge-your-car-like-your-phone-in-emergencies.html)"
              ],
              "S02E33": [
                "Enable the Home Assistant System Health Component (https://www.vcloudinfo.com/2019/09/how-to-enable-the-home-assistant-system-health-component.html)"
              ],
              "S02E34": [
                "Magic Home LED Fix & Great iOS Setup tip (https://www.vcloudinfo.com/2019/09/magic-home-led-fix-great-ios-setup-tip.html)"
              ],
              "S02E34": [
                "Alexa, Home Assistant & Nabu Casa (https://www.vcloudinfo.com/2019/09/help-alexa-forget-devices-to-hear-you-better-and-respond-more-accurately.html)"
              ]

            } %}

            {{ tweets[topic]|random ~ "#youtube #throwback" }}
          {%- endmacro -%}

          {{ tweet(pick) }}

        image: >-
          {% if pick == "Throwback" -%}
            "/config/www/custom_ui/floorplan/images/youtube/throwback.png"
          {%- else -%}
            {{ "\"/config/www/custom_ui/floorplan/images/youtube/episodes/" ~ pick ~ ".png\"" }}
          {%- endif -%}
